[app]
workspace = "/path/to/your/workspace"

[models.default]
provider = "openai"
model = "gpt-4o-mini"
max_tokens = 4096

[agents.default]
system_prompt = "You are a helpful coding and ops agent. Prefer tools when appropriate."
authorized_tools = ["shell_run", "fs_read", "fs_write"]

[tools.shell_run]
allow = ["python", "uv", "ls", "cat", "rg", "git", "pytest"]
deny = ["rm", "shutdown", "reboot", "mkfs"]